nakst/gf

- gf2.cpp
this should fix #6 by spawning gdb in a new session so it doesn't get resize event from the original terminal.
> fix gdb crash when resizing terminal 

- gf2.cpp
- luigi.h
This is two small changes, but if you want I can split it up in two pull requests.
- add the `_NET_WM_WINDOW_TYPE_DROPDOWN_MENU` flag to the menu button popup. 
This makes it behave like a menu instead of a separate window. This makes a pretty big difference on tiling window managers.
- pass additional command line args to the gdb process.
This lets you launch gf like `gf2 myProgram --someOther args` instead of having to call `file` and `set args`
> make menu pop behave better on tiling WMs and pass args to gdb

- gf2.cpp
I often close programs by doing a Ctrl-C in the terminal, but when I closed gf this way it leaves the gdb thread running.
This adds a signal handler to call CloseDebugger on SIGINT and terminate the gdb thread.
> cleanly close debugger on SIGINT

- luigi.h
This makes sure the menu window is drawn on top of gf even when in fullscreen.
> make menu work in full screen

- build.sh
Tried running ./build.sh but got 15 errors all like:
```
gf2.cpp: In function ‘char* LoadFile(const char*, size_t*)’:
gf2.cpp:239:7: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
239 |  fread(buffer, 1, bytes, f);
|  ~~~~~^~~~~~~~~~~~~~~~~~~~~
```
Adding this warning flag removed the errors and gf2 can be built successfully.
> Update warning flags. Add -Wno-unused-result

- gf2.cpp
- windows.cpp
It's often useful to see the source code interleaved with disassembly.
gdb has options for the "disas" command to accomplish this.
From the gdb output for "help disas":
With a /s modifier, source lines are included (if available).
In this mode, the output is displayed in PC address order, and
file names and contents for all relevant source files are displayed.
With a /m modifier, source lines are included (if available).
This view is "source centric": the output is in source line order,
regardless of any optimization that is present.  Only the main source file
is displayed, not those of, e.g., any inlined functions.
This modifier hasn't proved useful in practice and is deprecated
in favor of /s.
In this change, CTRL+M cycles between using "disas","disas /s","disas /m".
The default CTRL+D …
> Interleave disassembly with source using CTRL+M

- gf2.cpp
The gvim sync fuction only works in systems that are in English. The CommandSyncWithGvim was searching for the world **line** in the end of a vim command output. In systems that have other works for **line** the function fails.
I've made a small correction that change the function to be language agnostic.
Thanks for the software.
My best,
Rafael Sachetto
> Small bug correction with gvim sync in non-English systems

- gf2.cpp
- windows.cpp
MOTIVATION:
gf has become my go-to debugger front end, but I have always missed the "locals" view that many debuggers have. Without any prior experience with gdb's python API, I tried my hand at cobbling up a solution.
This isn't finished yet. I'm just sharing something I was trying to do in case there is interest in it, in which case I can work on it more.
USAGE:
As it stands, you can add the expression `.locals` to the watch panel to get a view of all of the local variables. The main problem right now is that the "fields" of the locals view don't seem to update when the scope changes unless you delete the expression and recreate it.
TODO:
> Local variables view

- gf2.cpp
I felt the `--help` to be lacking details on how to use, and didn't have the source code on hand to check the readme for super basic arguments.
I added the relevant information (the fact that it accepts any gdb arguments) to the `--help` print.
It looks like this:
```
$ ./gf2 --help
Usage: ./gf2 [GDB ARGS]
GDB ARGS: Pass any gdb arguments here, they will be forwarded to gdb.
For more information, view the README.md.
$ 
```
> Add usage details to `--help` argument

- gf2.cpp
- windows.cpp
- Implements copy to clipboard for watch values, addresses issue https://github.com/nakst/gf/issues/99
- This implementation doesn't take into account child expressions of the focused watch expression like save as does
> Implement copy watch value to clipboard, keyboard shortcut

- build_openbsd.sh
- gf2.cpp
- luigi2.h
Hi,
First off, thank you an amazing piece of software. I have tried a lot of GDB frontends over the years and I must say this one did it for me.
Anyways, here's a pull request that adds support for OpenBSD (tested on amd64 7.3-CURRENT). The changes are quite minor and shouldn't affect any other OS.
The commits themselves are documented with the necessary changes but in short, add a build script, change the variable that holds the name of the gdb executable
Please let me know if there's anything that needs fixing
> Add OpenBSD support

- windows.cpp
Otherwise a click on a thread to activate will not always work, e.g. when some threads have exited in between. The item index + 1 only workedy by accident when no thread exited or one has only one thread running. Tested with a simple program:
```cpp
#include <iostream>
#include <thread>
#include <unistd.h>
int main() {
std::cout << "hello threads\n";
for (int i = 0; i < 10; i++) {
std::thread fread([] { usleep(100000); });
fread.join();
}
std::cout << "goodbye threads\n";
return 0;
}
```
By breaking at fread.join(); and watching the thread list, and continuing by pressing `F5`
> Track threads by their assigned id from gdb

- README.md
- gf2.cpp
Hi,
I was debugging some large code base, and released that I'm not able to see the full stack trace, so decided to check why that is the case.
Personally, I do not see the use case when it would be useful to truncate the stack, but it's possible to make this as an option in config file.
Something like:
```
[gdb]
limit_stack_size = 50
```
What do you think?
> remove stack size limit

- build_openbsd.sh
The current build script for OpenBSD does not properly detect SSE2 support in the host CPU. It checks if the machine hardware name is x86_64, which is not a name that OpenBSD uses for any architecture. What uname on Linux reports as x86_64, OpenBSD's uname reports as amd64.
This new build script detects whether the host CPU is AMD64, and in that case defines UI_SSE2.
> Enable UI SSE2 for OpenBSD/amd64

- gf2.cpp
This commit fixes the following bug:
Adding the same `breakpoint` multiple times, adds multiple duplicate entries in the Breakpoints window.
Steps to reproduce:
1- `gf2 myprogram`
2- issue the following command multiple times: `b main`
3- click on the `Breakpoints` window on the right 
you will observe the same entry multiple times shown in the `Breakpoints` window.
> deduplicate redundant entries in the Breakpoints window.

- build_netbsd.sh
- gf2.cpp
The only issue with NetBSD right now is that they ship an older version of GCC (version 7.x from 2017). There are newer versions of GCC available in repo, however, I don't think it will come without creating conflict with the existing one. So instead I've "forced" clang in that script.
Some other changes included - adding the `__NetBSD__`  identifier macro and closing the file stream after ending using it (at main).
> Add NetBSD build script

- windows.cpp
Right now if we add a watch expression to inspect the contents of say an array in C ` char buffer[100];`, or just inspect it's contents  in the `Locals` window, and then change the format specifier of the buffer with for example `/x`, this will change it's display format to hexadecimal, but when expanded (`>`) all the elements in the array are not displayed in the hexadecimal format.
This pull request makes sure to synchronize the format of the different fields of the watch object with their parent.
> fix: display the expanded elements of an array in the right format.

- gf2.cpp
- windows.cpp
This feature adds the ability to enable/disable `breakpoints` and `watchpoints` by giving the user the option to do so in the right click menu of the `Breakpoints` window, and the left margin of the code view.
The marker on the left margin of the code view of disabled breakpoints will be indicated in a darker shade of red `0x520404`, and for the `Breakpoints` window we have added a new column ("Enabled") that will indicate with yes or no whether the breakpoint/watchpoint is enabled or disabled.
> feat: added the ability to enable/disable breakpoints and watchpoints

- README.md
- gf2.cpp
Basically, when passing arguments to gf they are properly parsed by the shell for us, but if we read gdb arguments from config they are not handled properly. This parsing is simple and surely does not handle some cases, but should be good enough.
Also with this change, it is possible to pass multiple arguments in a single argument variable
```
[gdb]
argument=-arg1 val1 -arg2 val2 -ex "set breakpoint ..."
```
#97
> Parse gdb argument from config files

- gf2.cpp
- windows.cpp
This PR adds the ability to delete, enable and disable multiple selected breakpoints at once.
The user can select multiple breakpoints by holding the CTRL key and clicking with the left mouse button on the desired breakpoints in the `Breakpoint` window, or by holding down the SHIFT key and selecting a desired range or breakpoints. Then if they choose in the right click menu to `Delete`, `Enable` or `Disable`, the action will affect all the selected breakpoints.
> feat: added the ability to enable, disable and delete multiple breakpoints at once

- windows.cpp
making sure to not index the breakpoints array at index = -1, otherwise core dump, and we do not like those.
> fix: accessing the breakpoints array at bad index value.

- gf2.cpp
I find myself trying to use these gdb shortcuts from muscle memory, i think we should add them to gf.
This PR adds these new keyboard shortcuts to the command textbox:
- `CTRL + p` : retrieve the previous command from the command history  (same as `UP`)
- `CTRL + n` : retrieve the next command from the command history  (same as `DOWN`)
- `CTRL + l` : clear command output
> feat: added gdb compatible keyboard shortcuts.

- gf2.cpp
- windows.cpp
As of right now we don't display conditional breakpoints in the Breakpoints window if there's already a breakpoint at the same line (ex: `b 34` followed by `b 34 if i > 19` will only show the 1st breakpoint in the Breakpoints window). 
This PR adds the ability to have multiple breakpoints at the same line if they have different conditions. To distinguish between them we have added a new column in the `Breakpoints` window to display the condition for each breakpoint.
Deleting, Disabling or Enabling a breakpoint from the marker on the left margin of the code view, will Delete, Disable or Enable all the breakpoints at that line respectively.
The breakpoint marker in the left margin of the code view will only showed in a disabled state if all the breakpoints points at that given line are …
> fix: handle conditional breakpoints correctly.

- gf2.cpp
- windows.cpp
Since we introduced the `number` field in the `Breakpoint` type, `watchpoint` can be simplified to a bool.
> refactor: convert watchpoint to a bool.

- luigi2.h
This PR closes #131.
this PR adds support for horizontal scrollbars for `UICode` elements by default (we got rid of the flag `UI_CODE_H_SCROLL` as discussed in [here](https://github.com/nakst/gf/issues/131#issuecomment-1742174032)). We also added a visual enhancement which consists on reclaiming the space occupied by the horizontal scrollbars when they are not needed (i.e. hidden).
> feat: added horizontal scrollbar support for `UICode` elements.

- gf2.cpp
The brackets in 'NotoSansMono[wght].ttf' were wrongly interpreted by grep as special regex characters, causing the match to fail and the fallback font to be used.
> Fix font-finding edgecase with special characters

- luigi2.h
the 1st commit just adds a text cursor for the `UICode` elements.
the 2nd commit fixes the following bug: when clicking on the left margin (to set a breakpoint), the first character of that line is selected.
> feat: some fixes and enhancements to the selection in the `UICode` elements.

- luigi2.h
When pasting for e.g., "test\n" to a UITextbox element a weird character is pasted at the end of the line, this commit fixes the said bug.
I discovered this bug by selecting a line of code all the way to the end in the code view, copying it, and then pasting it to the `textboxInput` where i observed a box like character printed in the textbox.
> fix: strip the `\n` character at the end of the pasted text in a `UITextbox` element.

- luigi2.h
When pasting text that contains a `\n` characters in it to `UITextbox` a weird character is inserted everywhere there's a new line character. To fix this we simply replace all occurrences of the `\n` character with a empty space.
> fix: handle `\n` characters when pasting to a `UITextbox` correctly.

- luigi2.h
This PR adds the ability to move the cursor's position in `UITextbox` elements by clicking with the left mouse button at any position to edit the textbox.
> feat: move the cursor around with the mouse in `UITextbox` elements.

- gf2.cpp
- luigi2.h
I believe the line numbers should not have the same color as the code lines, if we look at any text editor/IDE it's pretty much the case, so by default i set the color of the line numbers to be the same as the comments, if you you want me to change the default color please do tell. With this PR even if we disagree every user can customize their **gf** to their liking.
> NOTE: you'll need to update the [wiki](https://github.com/nakst/gf/wiki/Themes) examples
> feat: added the ability to customize the line numbers color.

- luigi2.h
- `Right arrow key`:  scroll to the right
- `Left arrow key`:   scroll to the left
- `Top arrow key`:    scroll to the top
- `Bottom arrow key`: scroll to the bottom
- `Page Up`:          scroll one page up
- `Page Down`:        scroll one page down
- `Home`:             scroll to the first row
- `End`:              scroll to the last row
> feat: added new keyboard shortcuts for scrolling in `UITable` elements.

- luigi2.h
This PR fix the following issue: 
If we change the scale value (for e.g., if we set `scale=2` under `[ui]` in `gf2_config.ini`) the last row doesn't show even if we scroll all the way down.
> fix: fixed a scaling issue with the vertical scrollbars of `UITable` elements.

- luigi2.h
When making a text selection outside of the visible area of `UICode` elements, scroll automatically the view horizontally and/or vertically as needed.
> feat: scroll text automatically when making a text selection outside of the visible area of `UICode` elements.

- luigi2.h
When a user left clicks in a `UICode` element before this PR, a single character is "fake" selected because when you copy and paste, nothing is pasted and in fact you can't select a single character and copy it at all. 
This PR introduces a cursor that is drawn when a user just left clicks in a `UICode` elements, and also fixed the issue mentioned above.
> feat: draw a cursor in `UICode` elements.

- luigi2.h
- `Shift + Left`: move the selection to the left
- `Shift + Right`: move the selection to the right
- `Shift + Up`: move the selection up
- `Shift + Down`: move the selection down
- `Shift + Home`: move the selection to the beginning of the line
- `Shift + End`: move the selection to the end of the line
- `Shift + Page Up`: move the selection one page up
- `Shift + Page Down`: move the selection one page down
- `Shift + Ctrl + Left`: move selection one word to the left
- `Shift + Ctrl + Right`: move selection one word to the right
> feat: added keyboard shortcuts for making selections in `UICode` elements.

- luigi2.h
The last commit broke the ability to right-click and disable/enable or delete breakpoints on the left margin, this PR fixed the said issue.
> fix: making sure to not show the copy context menu on the left margin.

- luigi2.h
This patch adds basic Unicode support to the UI. It relies on Freetype font renderer and is hidden by default behind UI_UNICODE flag. Encoding support is currently limited to UTF-8.
What works:
- Display of all Unicode characters. Tested against (https://github.com/bits/UTF-8-Unicode-Test-Documents/blob/master/UTF-8_sequence_separated/utf8_sequence_0-0x10ffff_assigned_including-unprintable-asis.txt) and (https://github.com/bits/UTF-8-Unicode-Test-Documents/blob/master/UTF-8_sequence_separated/utf8_sequence_0-0x10ffff_assigned_including-unprintable-replaced.txt)
- Handling of invalid UTF-8 input. Invalid characters are replaced with `?` without any other adverse effects.
- Navigation in text using keyboard and mouse, selection, copy-paste, replacements.
- Starting executables from paths …
> Add basic Unicode support

- gf2.cpp
This is necessary for rust-gdb to work since that is just a symlink to rustup which will select the correct rust-gdb installation at runtime. (Technically, you try to find the path to the actual rust-gdb binary somewhere in ~/.rustup and use that).
In addition, setting argv[0] to the program filename is what most programs should expect anyway.
> Also set gdbArgv[0] when loading gdb path from settings

- windows.cpp
Hi, I know I'm the one who changed the thread views 'Frame' string last but I recently got an aarch64 laptop and while running gf on it I noticed what I was doing was incorrect. I also realized it was incorrect for the main thread on amd64 because GDB special cases the thread which contains the 'main' function in it's frame.
I've tested this on both amd64 and aarch64 and this gives the correct results in both cases (just the function's name on aarch64 and the function's address and name on amd64 excluding the main thread which doesn't list the function's address).
> properly skip leading spaces in Frame string

- gf2.cpp
The watch window fails with the following Python exception:
```
Python Exception <class 'AttributeError'>: module 'gdb' has no attribute 'types'
````
Seems like it was probably caused by some update to how gdb manages its internal python libraries. Simply adding an `import gdb.types` at the top of the python code part like shown [here](https://sourceware.org/gdb/current/onlinedocs/gdb.html/gdb_002etypes.html#gdb_002etypes) fixed it for me.
Distro: Arch Linux
GDB version: 16.1
Python version: 3.13.1
> Fixed python exception in watch window

- gf2.cpp
Hi!
I recently needed to customize my UI layout, but I found it a bit tedious to modify position numbers directly. So I thought what if you could serialize the UI layout back to a string and put it into the clipboard, so you could adjust positions in WYSIWYG style and then just copy-paste the layout string to your config? So I implemented it. It was pretty convenient. Here is a demo:
https://github.com/user-attachments/assets/3e99c471-2490-44a0-8e2c-1ff7e1affde3
It would be kinda cool if the layout string was automatically saved to the config, but I decided not to implement this because maybe the config is meant to be modified manually and it's rude for the program to mess with it, I dunno.
Please let me know if there are any problems with the approach. I'm ready to fix them. Feel free to …
> Implement "Copy Layout to Clipboard" functionality

- README.md
Updated the description of the `layout` parameter of the `[ui]` section for the config. The argument of the `h` function were left and right instead of up and down, which is confusing.
> Changed the description of the h() function for the layout in the README
